version: 2
jobs:
  release:
    docker:
      - image: circleci/golang:1.12
    steps:
      - attach_workspace:
          at: '~/project'
      - setup_remote_docker
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: docker build -t hacdias/caddy-plugin-test .
      - run: docker push hacdias/caddy-plugin-test
      - run: docker logout
workflows:
  version: 2
  deploy:
    jobs:
      - release:
          context: deploy
